### ISSUE TITLE
balance not updated after sending

### ISSUE THREAD

**Issue by abgit** [voisine/breadwallet#378]
Hi all,
Seems that balance is not instantly updated after sending btc.

using latest version (0.6)

**Comment by abgit** [comment]
seems fixed on v0.6.1

**Comment by voisine** [comment]
Thanks, this was fixed by b748308

**Comment by leoncfu** [comment]
Aaron,

I think there is a bug. Someone reused an address and sent me more Bitcoins using the same address. Breadwallet didn’t add up the balance correctly as you can see from the screenshot. I still have 6 BTC after someone sent me 4.5 BTC.

Leon

**Comment by leoncfu** [comment]
That worked! Thanks! I tried to do a rescan and it didn’t fix the problem.

Leon

On Jun 10, 2016, at 5:02 PM, Aaron Voisine <notifications@github.com> wrote:

Try killing/restarting the app. I'll be pushing an update to the app store shortly. It only happens on transactions that use nLockTime.
